name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./GitActionApp/
    - name: Build
      run: dotnet build --no-restore  ./GitActionApp/
    - name: Publish application
      run: dotnet publish "./GitActionApp/" -c Release -o myApp
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: simpleaspnetapp-artifact
       path: "./myApp"
    - name: Copy file
      # You may pin to the exact commit or the version.
      # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: "./myApp"
        # Target file
        target:  "C:/_dev/aspnetcoreapp/dest"
