name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./GitActionApp/
    - name: Build
      run: dotnet build --no-restore  ./GitActionApp/
    - name: Publish application
      run: dotnet publish "./GitActionApp/" -c Release -o myApp
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: simpleaspnetapp-artifact
       path: "./myApp"
    - name: PowerShell script
      # You may pin to the exact commit or the version.
      # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: Copy-Item "C:\actions-runner\_work\action_runner\action_runner\myApp\*" -Destination "C:\_dev\aspnetcoreapp\dest"
                    
